datagouvfr:
  # data.gouv.fr base URL
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id:
  # pkce client secret, explicitely public
  oauth_client_secret:

universe:
  # "universe" topic id
  topic_id: 65141cd780d73f98142e9265 # meteo-test
  # universe name, used as bouquets tag
  name: acteurs-publics

# UI customizations
website:
  title: 'acteurs-publics.data.gouv.fr'
  rf_title: 'R√âPUBLIQUE<br>
    FRAN√áAISE'
  service_logo: '/logos/acteurs-publics-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent

  homepage:
    title: 'Acteurs publics, utilisez la donn√©e pour simplifier vos services üßò !'
    subtitle: 'Simplifiez les d√©marches et services des citoyens, entreprises et associations en r√©cup√©rant pour eux leurs informations administratives gr√¢ces aux API et aux donn√©es ! Vous gagnerez aussi du temps !'
    sections:
      # - title: Section 1
      #   content: >-
      #     ## Am√©liorer les services √† destination :

      #     ### üë± des particuliers

      #     Simplifiez les d√©marches des citoyens et facilitez l'instruction de leurs dossiers :

      #   sub_section_datasets:
      #     title: "Jeux de donn√©es"
      #     datasets:
      #       - "5b7ffc618b4c4169d30727e0"
      #       - "621df2954fa5a3b5a023e23c"
      #   sub_section_cards:
      #     title: "Th√©matiques"
      #     cards:
      #       - id: '65f170136c6ff1b1d0351081'
      #         name: 'March√©s publics'
      #         description: "list des march√©s publics. list des march√©s publics. list des march√©s publics. list des march√©s publics. "
      #         url: 'https://www.google.com/'
      #         image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_ecole4.png'
      #       - id: '65f170136c6ff1b1d0351081'
      #         name: 'Coucou nouveau'
      #         description: "list des march√©s publics. list des march√©s publics. list des march√©s publics. list des march√©s publics."
      #         url: 'bouquets/65f170136c6ff1b1d0351081'
      #         image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_ecole4.png'
      #   sub_section_tiles:
      #     title: "Th√©matiques 2"
      #     tiles:
      #       - id: '65f170136c6ff1b1d0351081'
      #         name: 'March√©s publics'
      #         description: "list des march√©s publics. list des march√©s publics. list des march√©s publics. list des march√©s publics. "
      #         url: 'https://www.google.com/'
      #       - id: '65f170136c6ff1b1d0351081'
      #         name: 'Coucou nouveau'
      #         description: "list des march√©s publics. list des march√©s publics. list des march√©s publics. list des march√©s publics."
      #         url: 'bouquets/65f170136c6ff1b1d0351081'
      # sub_section_buttons:
      #   - name: "Tout savoir sur les cas d'usages de particuliers"
      #     url: "bouquets?theme=Administrations&subtheme=Particuliers"
      #     class: "fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill"
      - title:
        content: >-
          ## Am√©liorer les services √† destination :

          ### üë± Des particuliers

          Les jusitificatifs demand√©s aux familles (quotient familial, certificat de scolarit√©, etc.) pour de nombreuses d√©marches sont souvent d√©j√† connus des services de l'√âtat ! Utilisez les tuyaux informatiques (API) √† votre disposition pour simplifier leurs d√©marches et acc√©l√©rer votre instuction :
        sub_section_cards:
          title:
          cards:
            - id: '660ac80b9e9351349f5c1f14'
              name: 'Tarification cantine des coll√®ges et lyc√©es'
              description: "D√©partements et r√©gions, simplifiez les d√©marches des familles en calculant automatiquement le tarif de restauration scolaire des coll√©giens et lyc√©ens"
              url: 'bouquets/tarification-cantine-des-colleges-et-lycees'
              image_url: '/acteurs-publics/assets/tarification_cantine.jpg'
            - id: '660ac8ab8fd1a813e28cecd2'
              name: 'Portail famille des communes'
              description: "Communes et intercommunalit√©s, simplifiez les d√©marches des familles en calculant automatiquement leur tarif de restauration scolaire, de cr√®ches ou d'activit√©s p√©riscolaires ou municipales."
              url: 'bouquets/portail-famille-des-communes'
              image_url: '/acteurs-publics/assets/portail_famille.jpg'
            - id: '660ac92bc20e599f930bb9c2'
              name: 'Tarification sociale et solidaire des transports'
              description: "AOM, obtenez automatiquement les donn√©es n√©cessaires √† l'attribution des tarifs r√©duits de transports collectifs."
              url: 'bouquets/tarification-sociale-et-solidaire-des-transports'
              image_url: '/acteurs-publics/assets/transport.jpg'
        sub_section_buttons:
          - name: "Tous les cas d'usages de particuliers"
            url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill'
          - name: "Pas de service informatique ? D√©couvrir les solutions cl√© en main"
            url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill fr-btn--secondary'
      - title:
        content: >-
          ### üíº des entreprises

          Simplifiez les d√©marches des entreprises et facilitez l'instruction de leurs dossiers :

        sub_section_cards:
          title:
          cards:
            - id: '5e6f426e634f417810ab794b'
              name: 'March√©s publics'
              description: 'Tout savoir sur les march√©s publics pass√©s par les collectivit√©s.'
              url: 'bouquets/marches-publics-1'
              image_url: '/acteurs-publics/assets/marches.png'
            - id: '65f170136c6ff1b1d0351081'
              name: 'Donn√©es fiscales'
              description: 'Acc√©der aux comptes et documents financiers des entreprises'
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/acteurs-publics/assets/fiscales.png'
            - id: '65f170136c6ff1b1d0351081'
              name: 'Informations l√©gales'
              description: "Acc√©der √† l'ensemble des informations l√©gales des entreprises."
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/acteurs-publics/assets/documents.png'
        sub_section_buttons:
          - name: "Tous les cas d'usages d‚Äôentreprises"
            url: 'bouquets?theme=Administrations&subtheme=Entreprises'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill'
          - name: "Pas de service informatique ? D√©couvrir les solutions cl√© en main"
            url: 'bouquets?theme=Administrations&subtheme=Entreprises'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill fr-btn--secondary'
      - title:
        content: >-
          ### üé≠ des associations

          Simplifiez les d√©marches des associations et facilitez l'instruction de leurs dossiers :

        sub_section_cards:
          title:
          cards:
            - id: '65f170136c6ff1b1d0351081'
              name: 'Documents associations'
              description: "Tout savoir sur les documents d'une association."
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/acteurs-publics/assets/documents.png'
            - id: '65f170136c6ff1b1d0351081'
              name: 'Dirigeants associatifs'
              description: "Acc√©der √† la liste des dirigeants d'une association."
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/acteurs-publics/assets/dirigeants.png'
        sub_section_buttons:
          - name: "Tous les cas d'usages d‚Äôassociations"
            url: 'bouquets?theme=Administrations&subtheme=Associations'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill'
          - name: "Pas de service informatique ? D√©couvrir les solutions cl√© en main"
            url: 'bouquets?theme=Administrations&subtheme=Associations'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill fr-btn--secondary'
      - title:
        content: >-
          ## Quelques soient vos moyens techniques, une solution

          <p class="fr-text--lg">
          Ce portail s'adresse √† l'ensemble des acteurs publics, qu'ils disposent ou non d'un service informatique ou d'un prestataire.
          <br/>
          Pour chacun des cas d'usages, un indicateur vous permet de savoir quelles sont les possibilit√©s d'int√©gration :
          </p> 
          

          - **Solution cl√© en main** : Une solution cl√© en main est disponible pour ce cas d'usage. Si vous n'avez pas ni service informatique ni comp√©tences techniques, vous pouvez donc utiliser la solution cl√© en main pour couvrir le cas d'usage. 

          - **Solutions √©diteurs** : Des √©diteurs proposent des logiciels permettant de couvrir ce cas d'usage.



        sub_section_cards:
          title:
          cards:
            - name: 'Vous n‚Äôavez ni √©quipe technique, ni √©diteur'
              description: "Les cas d'usage accessibles avec des solutions cl√©s en main, faciles √† mettre en place par un agent non technique."
              url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            - name: 'Vous passez par un √©diteur'
              description: "Les cas d'usages port√©s par des √©diteurs qui s'occupent de l'int√©gration."
              url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            - name: 'Vous avez votre service informatique'
              description: "Les cas d'usages que vos services informatiques peuvent int√©grer dans vos d√©marches et/ou votre syst√®me d‚Äôinformation."
              url: 'bouquets?theme=Administrations&subtheme=Particuliers'
      - title:
        content: >-
          ## Comment et pourquoi simplifier vos d√©marches ?

          <p class="fr-text--lg">
          Administrations et collectivit√©s, en int√©grant des API ou des donn√©es dans vos d√©marches et/ou votre syst√®me d‚Äôinformation :
          </p>

          - üóÑ **Vous acc√©dez facilement aux donn√©es administratives de vos usagers**, qu'elles soient publiques ou prot√©g√©es et provenant de [nombreux fournisseurs](/organizations) ;


          - ‚è∞ **Vous acc√©l√©rez le traitement des d√©marches car vos agents instructeurs** n‚Äôont pas de v√©rifications suppl√©mentaires √† r√©aliser, les informations obtenues que nous vous recommandons sont certifi√©es üîé ;


          - üé¢ **Vous augmentez le pourcentage des d√©marches finalis√©es** car vous fa√Ætes gagner du temps √† l‚Äôusager ;


          - üéØ **Vous participez activement √† la simplification des d√©marches en mettant en place le ¬´ _[Dites-le-nous une fois](/dlnuf)_ ¬ª** : vous ne demandez plus √† vos usagers une information qu‚Äôils ont d√©j√† donn√©e ou que l‚Äôadministration conna√Æt d√©j√†. Vous vous mettez ainsi en conformit√© avec la l√©gislation et, plus particuli√®rement l‚Äô[Article L113-12 du Code des relations entre le public et l‚Äôadministration](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037313155).


          - üíå **Vous r√©duisez le taux de non recours**, plus particuli√®rement si vous mettez en place des d√©marches proactives. [En savoir plus sur la proactivit√©](/proactivite).


          Pour en savoir plus, consultez nos [guides de la simplification](/guides).
  header_button:
    display: true
    label: 'Compte Datapass'
    link: https://datapass.api.gouv.fr/
  search_bar:
    display: false
    placeholder: 'Rechercher un jeu de donn√©es'
  secondary_search:
    display: false
    name: 'Recherche guid√©e'
    link: '/form'
  router_items:
    - name: 'Accueil'
      id: 'home'
      linkPage: '/'
      type: 'component'
      display_menu: false
    - name: 'Cas d‚Äôusages'
      id: 'bouquets'
      linkPage: '/bouquets'
      type: 'component'
      display_menu: true
    - name: 'Les solutions'
      id: 'guides'
      linkPage: '/solutions'
      type: 'page'
      url: '/acteurs-publics/pages/solutions.md'
      display_menu: true
    - name: 'Guides de la simplification'
      id: 'guides'
      linkPage: '/guides'
      type: 'page'
      url: '/acteurs-publics/pages/guides.md'
      display_menu: true
    - name: 'Toutes les API & donn√©es utiles'
      id: 'datasets'
      linkPage: '/datasets'
      type: 'component'
      display_menu: true
    - name: 'Accessibilit√©'
      id: 'accessibility'
      linkPage: '/accessibility'
      type: 'page'
      display_menu: false
      url: '/acteurs-publics/pages/accessibility.md'
    - name: 'Organisations'
      id: 'organizations'
      linkPage: '/organizations'
      type: 'component'
      display_menu: false
  show_topic_charts: true
  show_quality_component: true
  show_dataset_metadata_panel: false
  oauth_option: false
  footer_phrase: 'Ce site permet aux administrations et collectivit√©s territoriales de conna√Ætre les API et les donn√©es qui leur permettent de simplifier leurs d√©marches pour les particuliers, les entreprises et les associations.'
  footer_external_links:
    - label: 'API Entreprise'
      href: 'https://www.entreprise.api.gouv.fr'
    - label: 'API Particulier'
      href: 'https://www.particulier.api.gouv.fr'
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions g√©n√©rales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialit√©'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilit√© : non conforme'
      to: '/accessibility'
  logo_operator: ''
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  home_banner_colors:
    - '#D6DAF7'
    - '#DBA8A8'
    - '#A25070'
  env: 'dev'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 292
  discussions:
    dataset:
      display: true
      create: false
    topic:
      display: false
      create: false
  datasets:
    organization_filter: false
    add_to_bouquet: false
organizations:
  # list of organisations' ids that should be handled by the portal
  # to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
  # then Informations > ID at the bottom of the page
  # # Dinum
  # - 57fe2a35c751df21e179df72
  # # Insee
  # - 534fff81a3a7292c64a77e5c

themes:
  - name: Administrations
    color: 043574
    textColor: FFFFFF
    subthemes:
      - name: Entreprises
      - name: Associations
      - name: Particuliers
  - name: Communes
    color: 043574
    textColor: FFFFFF
    subthemes:
      - name: Entreprises
      - name: Associations
      - name: Particuliers
  - name: D√©partements
    color: 1E929E
    subthemes:
      - name: Entreprises
      - name: Associations
      - name: Particuliers
  - name: R√©gions
    color: 1E929E
    subthemes:
      - name: Entreprises
      - name: Associations
      - name: Particuliers
  - name: Op√©rateurs de l'√âtat
    color: 1E929E
    subthemes:
      - name: Entreprises
      - name: Associations
      - name: Particuliers
bouquets:
  steps:
  type: 'data.gouv.fr' #data.gouv.fr or custom
  display_author: false
  theme:
    name: "Vous √™tes :"
    placeholder: Choisir un type d'organisation
  subtheme:
    name: "Votre service s'adresse √† :"
    placeholder: Choisir un type d'usager
## Ici il faut pouvoir ajouter un autre filtre qui indique les moyens d'int√©ration disponibles (sans √©quipe tech sans √©diteur | avec √©diteur | autonome)