# config file for simplification

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id:

universe:
  # "universe" topic id
  topic_id: 65141cd780d73f98142e9265
  # universe name, used as bouquets tag
  name: simplification

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'simplification.data.gouv.fr'
  formatted_title: '<i>simplification.</i><b>data.gouv</b><i>.fr</i>'
  rf_title: 'R√âPUBLIQUE<br>
    FRAN√áAISE'
  service_logo: '/logos/simplification-logo.svg'
  badge:
    display: false
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  homepage:
    title: 'Acteurs publics, utilisez la donn√©e pour simplifier vos services üßò !'
    subtitle: 'Simplifiez les d√©marches et services des citoyens, entreprises et associations en r√©cup√©rant pour eux leurs informations administratives gr√¢ces aux API et aux donn√©es ! Vous gagnerez aussi du temps !'
    sections:
      - title:
        content: >-
          ## Am√©liorer les services √† destination :

          ### üë± Des particuliers

          Les jusitificatifs demand√©s aux familles (quotient familial, certificat de scolarit√©, etc.) pour de nombreuses d√©marches sont souvent d√©j√† connus des services de l'√âtat ! Utilisez les tuyaux informatiques (API) √† votre disposition pour simplifier leurs d√©marches et acc√©l√©rer votre instuction :
        sub_section_datasets:
        #     title: "Jeux de donn√©es"
        #     datasets:
        #       - "5b7ffc618b4c4169d30727e0"
        #       - "621df2954fa5a3b5a023e23c"
        sub_section_cards:
          title:
          cards:
            - id: '660ac80b9e9351349f5c1f14'
              name: 'Tarification cantine des coll√®ges et lyc√©es'
              description: 'D√©partements et r√©gions, simplifiez les d√©marches des familles en calculant automatiquement le tarif de restauration scolaire des coll√©giens et lyc√©ens'
              url: 'bouquets/tarification-cantine-des-colleges-et-lycees'
              image_url: '/simplification/assets/tarification_cantine.jpg'
            - id: '660ac8ab8fd1a813e28cecd2'
              name: 'Portail famille des communes'
              description: "Communes et intercommunalit√©s, simplifiez les d√©marches des familles en calculant automatiquement leur tarif de restauration scolaire, de cr√®ches ou d'activit√©s p√©riscolaires ou municipales."
              url: 'bouquets/portail-famille-des-communes'
              image_url: '/simplification/assets/portail_famille.jpg'
            - id: '660ac92bc20e599f930bb9c2'
              name: 'Tarification sociale et solidaire des transports'
              description: "AOM, obtenez automatiquement les donn√©es n√©cessaires √† l'attribution des tarifs r√©duits de transports collectifs."
              url: 'bouquets/tarification-sociale-et-solidaire-des-transports'
              image_url: '/simplification/assets/transport.jpg'
        sub_section_tiles:
        sub_section_buttons:
          - name: "Tous les cas d'usages de particuliers"
            url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill'
          - name: 'Pas de service informatique ? D√©couvrir les solutions cl√© en main'
            url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill fr-btn--secondary'
      - title:
        content: >-
          ### üíº des entreprises

          Simplifiez les d√©marches des entreprises et facilitez l'instruction de leurs dossiers :
        sub_section_datasets:
        sub_section_cards:
          title:
          cards:
            - id: '5e6f426e634f417810ab794b'
              name: 'March√©s publics'
              description: 'Tout savoir sur les march√©s publics pass√©s par les collectivit√©s.'
              url: 'bouquets/marches-publics-1'
              image_url: '/simplification/assets/marches.png'
            - id: '65f170136c6ff1b1d0351081'
              name: 'Donn√©es fiscales'
              description: 'Acc√©der aux comptes et documents financiers des entreprises'
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/simplification/assets/fiscales.png'
            - id: '65f170136c6ff1b1d0351081'
              name: 'Informations l√©gales'
              description: "Acc√©der √† l'ensemble des informations l√©gales des entreprises."
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/simplification/assets/documents.png'
        sub_section_tiles:
        sub_section_buttons:
          - name: "Tous les cas d'usages d‚Äôentreprises"
            url: 'bouquets?theme=Administrations&subtheme=Entreprises'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill'
          - name: 'Pas de service informatique ? D√©couvrir les solutions cl√© en main'
            url: 'bouquets?theme=Administrations&subtheme=Entreprises'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill fr-btn--secondary'
      - title:
        content: >-
          ### üé≠ des associations

          Simplifiez les d√©marches des associations et facilitez l'instruction de leurs dossiers :
        sub_section_datasets:
        sub_section_cards:
          title:
          cards:
            - id: '65f170136c6ff1b1d0351081'
              name: 'Documents associations'
              description: "Tout savoir sur les documents d'une association."
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/simplification/assets/documents.png'
            - id: '65f170136c6ff1b1d0351081'
              name: 'Dirigeants associatifs'
              description: "Acc√©der √† la liste des dirigeants d'une association."
              url: 'bouquets/65f170136c6ff1b1d0351081/'
              image_url: '/simplification/assets/dirigeants.png'
        sub_section_tiles:
        sub_section_buttons:
          - name: "Tous les cas d'usages d‚Äôassociations"
            url: 'bouquets?theme=Administrations&subtheme=Associations'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill'
          - name: 'Pas de service informatique ? D√©couvrir les solutions cl√© en main'
            url: 'bouquets?theme=Administrations&subtheme=Associations'
            class: 'fr-btn fr-btn--icon-left fr-btn--lg fr-icon-checkbox-circle-fill fr-btn--secondary'
      - title:
        content: >-
          ## Quelques soient vos moyens techniques, une solution

          <p class="fr-text--lg">
          Ce portail s'adresse √† l'ensemble des acteurs publics, qu'ils disposent ou non d'un service informatique ou d'un prestataire.
          <br/>
          Pour chacun des cas d'usages, un indicateur vous permet de savoir quelles sont les possibilit√©s d'int√©gration :
          </p>


          - **Solution cl√© en main** : Une solution cl√© en main est disponible pour ce cas d'usage. Si vous n'avez pas ni service informatique ni comp√©tences techniques, vous pouvez donc utiliser la solution cl√© en main pour couvrir le cas d'usage.

          - **Solutions √©diteurs** : Des √©diteurs proposent des logiciels permettant de couvrir ce cas d'usage.

        sub_section_datasets:
        sub_section_cards:
          title:
          cards:
            - name: 'Vous n‚Äôavez ni √©quipe technique, ni √©diteur'
              description: "Les cas d'usage accessibles avec des solutions cl√©s en main, faciles √† mettre en place par un agent non technique."
              url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            - name: 'Vous passez par un √©diteur'
              description: "Les cas d'usages port√©s par des √©diteurs qui s'occupent de l'int√©gration."
              url: 'bouquets?theme=Administrations&subtheme=Particuliers'
            - name: 'Vous avez votre service informatique'
              description: "Les cas d'usages que vos services informatiques peuvent int√©grer dans vos d√©marches et/ou votre syst√®me d‚Äôinformation."
              url: 'bouquets?theme=Administrations&subtheme=Particuliers'
        sub_section_tiles:
        sub_section_buttons:
      - title:
        content: >-
          ## Comment et pourquoi simplifier vos d√©marches ?

          <p class="fr-text--lg">
          Administrations et collectivit√©s, en int√©grant des API ou des donn√©es dans vos d√©marches et/ou votre syst√®me d‚Äôinformation :
          </p>

          - üóÑ **Vous acc√©dez facilement aux donn√©es administratives de vos usagers**, qu'elles soient publiques ou prot√©g√©es et provenant de [nombreux fournisseurs](/organizations) ;


          - ‚è∞ **Vous acc√©l√©rez le traitement des d√©marches car vos agents instructeurs** n‚Äôont pas de v√©rifications suppl√©mentaires √† r√©aliser, les informations obtenues que nous vous recommandons sont certifi√©es üîé ;


          - üé¢ **Vous augmentez le pourcentage des d√©marches finalis√©es** car vous fa√Ætes gagner du temps √† l‚Äôusager ;


          - üéØ **Vous participez activement √† la simplification des d√©marches en mettant en place le ¬´ _[Dites-le-nous une fois](/dlnuf)_ ¬ª** : vous ne demandez plus √† vos usagers une information qu‚Äôils ont d√©j√† donn√©e ou que l‚Äôadministration conna√Æt d√©j√†. Vous vous mettez ainsi en conformit√© avec la l√©gislation et, plus particuli√®rement l‚Äô[Article L113-12 du Code des relations entre le public et l‚Äôadministration](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037313155).


          - üíå **Vous r√©duisez le taux de non recours**, plus particuli√®rement si vous mettez en place des d√©marches proactives. [En savoir plus sur la proactivit√©](/proactivite).


          Pour en savoir plus, consultez nos [guides de la simplification](/guides).
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description:
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  header_search:
    display: false
    placeholder: Rechercher...
  search_bar:
    display: true
    placeholder: 'Rechercher un jeu de donn√©es'
  secondary_search:
    display: false
    name:
    link:
  menu:
    - text: Donn√©es
      to: /datasets
  router:
    disable:
      - organizations_routes
      - topics
    pages:
  show_quality_component: true
  list_search_topics:
  url_search_topics: 'datasets'
  oauth_option: false
  footer_phrase: 'Ce site est une d√©clinaison th√©matique de data.gouv.fr'
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions g√©n√©rales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialit√©'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilit√© : non conforme'
      to: '/accessibility'
  logo_operator:
  notice:
    display: false
    content: Notice avec un [lien beta](/beta) et du _style_
    closeable: false
  # debounce high enough for accessibility (screen readers will announce results)
  default_debounce_wait: 600
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 20
    files_list: 6
  home_banner_colors:
    - '#D6DAF7'
    - '#DBA8A8'
    - '#A25070'
  env: 'demo'
  matomo:
    host:
    siteId:
  discussions:
    dataset:
      display: true
      create: false
    topic:
      display: false
      create: false
  datasets:
    organization_filter: false
    add_to_bouquet: false
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning: []
    show_extended_information_panel: false
  topics:
    slug: usecases
    name: cas d'usage
    extras_key: 'ecospheres'
    themes:
      usage: true
      main_name: domaine
      secondary_name: sous-domaine
    # include a list page with all topics
    list_all: false
    display_metadata: false
    activate_read_more: false
    dataset_editorialization: false
    can_add_topics:
      everyone: false
      authorized_users:
        - 6230733357772160a4f77fba
# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:
